on:
  workflow_dispatch:

permissions:
  contents: read

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JBR
        uses: actions/setup-java@v4
        with:
          distribution: "jetbrains"
          java-package: "jdk"
          java-version: "21"
          check-latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Gradle (with cache)
        uses: gradle/actions/setup-gradle@v4

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK packages
        shell: bash
        run: |
          sdkmanager --install "platforms;android-36" "build-tools;36.1.0"

      - name: Build Debug APK
        shell: bash
        run: |
          ./gradlew :app:assembleDebug

      - name: Stop Gradle Daemons
        shell: bash
        run: |
          ./gradlew -stop

      - name: Upload Android artifact (arm64-v8a)
        uses: actions/upload-artifact@v4
        with:
          path: ./app/build/outputs/apk/debug/*arm64-v8a*.apk
          name: app-android-arm64-v8a
          if-no-files-found: error

      - name: Upload Android artifact (armeabi-v7a)
        uses: actions/upload-artifact@v4
        with:
          path: ./app/build/outputs/apk/debug/*armeabi-v7a*.apk
          name: app-android-armeabi-v7a
          if-no-files-found: error

      - name: Upload Android artifact (universal)
        uses: actions/upload-artifact@v4
        with:
          path: ./app/build/outputs/apk/debug/*universal*.apk
          name: app-android-universal
          if-no-files-found: error
